### ISSUE TITLE
Nothing happens unless you run it with sudo

### ISSUE THREAD

**Issue by clapbr** [germag/clicklockd#1]
First of all thank you very much for this. I've been suffering for years to find this feature in any OS other than Windows. I am disabled (quadriplegic) and use a trackball and need this to use my PC properly, I was essentially vendor-locked since my accident in 2009. 

Now back to the topic: not really a bug but it would be nice if the program showed any kind of message if you don have root privs, since it seems to be needed. When I run clicklockd without sudo it just terminates silently.

Last but not least importantly, why is this not implemented yet in any distro or directly in the libinput/udev driver? It was a miracle I randomly searched for clicklock on Github and found this. I don´t have C skills but I had patched gnome/mousetweaks but it barely worked and I gave up since the code was a bit complicated and involved threading. 

If you ever come to Rio/Brazil let me pay you a caipirinha. 
Bruno

**Comment by vipau** [comment]
This is because you don't have the permission to create the pidfile

Try running it with `-p` and giving it a path to a pidfile inside your home

**Comment by germag** [comment]
Hi @clapbr 
I apologise for replying so late, I wasn't even aware of anyone using it.
Regarding of clicklockd, it needs root permission for pid file creation (as @paualberto says), but also
for creating the virtual mouse, you can look at it:
$ ls -l /dev/uinput 
crw------- 1 root root 10, 223 mar 16 10:24 /dev/uinput

CLKD needs to write in that file (I'll look for other options).

Also, I'm working on fixing the error report problem, meanwhile you can check for errors within syslog files.
$ grep clicklockd /var/log/syslog

**Comment by vipau** [comment]
Hi @germag ,
I was able to run this without root by passing `-p`, not sure how I got to create the mouse device without root, but I guess it has something to do with udev or a user group (like belonging to the `input` group)

**Comment by germag** [comment]
Sorry it took me so long to fix this, I replaced all syslog calls with a simple print to standard error, I plan to extend the logger to support syslog and different log levels, but at least you can get a proper error and info y you run clicklockd in the terminal.
