### ISSUE TITLE
Does not work well when using Left handed mode

### ISSUE THREAD

**Issue by Cv03** [germag/clicklockd#10]
Just like said by title.
As a workaround, I use [input remapper](https://github.com/sezanzeb/input-remapper) to *reverse* left and right buttons.

Environments I have tried: Ubuntu with Gnome, Mint with Cinnamon, and Manjaro with KDE. All with latest updates.

**Comment by germag** [comment]
Hi,

I can add an option to define the primary button left or right, would it work for you?
I'm not sure if I will be able to automatically detect the DE mouse configuration.

**Comment by Cv03** [comment]
Yes, and I am afraid that manually defining the primary button is the ONLY solution.

I have tried the `xinput` command, which contains the left handed mode state value and a function it provides to remap buttons (at a driver layer, not to be confused with the input remapper above); it does not work either, and furthermore, results in a very strange behavior.

**Comment by germag** [comment]
Sorry for taking so much time to fix this.
Now you can use the `--left-handed` to set the right button as the primary button.
