### ISSUE TITLE
Fractional timeout

### ISSUE THREAD

**Issue by clapbr** [germag/clicklockd#2]
I tried to use fractional timeouts and after a quick glance at the source I realized it is implemented as a integer and with my C ignorance I tried changing all references of it to a float and it didnt work probably because of fsm.h #define EVENT_TIME(ev) ((ev)->time.tv_sec). Can you take a look and see if its easy to patch? thank you

**Comment by germag** [comment]
Hi @clapbr 
Would it be aceptable if I add time units (e.g. ms and us) intead of a fractional timeout?.

**Comment by clapbr** [comment]
> Hi @clapbr
> Would it be aceptable if I add time units (e.g. ms and us) intead of a fractional timeout?.

Yes, that would allow a bit more precision with the delay. ATM it has to be either too short or a bit too long .

**Comment by germag** [comment]
Hi @clapbr
I did both fractional timeout and units of time, now -t 1.6754, -t 1.6754s and -t 1675.4ms are all the same
best

**Comment by clapbr** [comment]
Nice! Using it already, seems to be working perfectly. The fine-grained delay is really more confortable to use (I had to hold the click a bit too long to trigger the lock).

We should try to put this in distros, I´ m sure many people would benefit from this accessibility feature and it´s not obvious for most people how to find this project, build it etc. It´s also really stable,  I've been using it for almost a year for 12h/day for work and gaming and it never bugged or crashed. With a bit of polish (maybe using systemd units to daemonize?) this can be easily considered production-ready.

edit: a had an issue due to my own fault, - forgot to update my startup script, disregard what I had posted below.

**Comment by clapbr** [comment]
After using it for a bit I found an issue: Try to double-click or triple-click a few times and it randomly triggers the lock, also triggering too early sometimes but I´ m not sure exactly when.

**Comment by germag** [comment]
Great! :)
You are right about packaging, that was my intention from the beginning. I guess it'll be systemd "friendly" once the issue #1 is closed. Since, for systemd daemons fprintf(stderr, fmt, ...) is preferred instead of syslog() (my plan is to use syslog() only if -b is given). But first I'll update the documentation (including a TODO list).

After that I will provide packages for multiple Linux distributions using The Open Build Service (OBS) by OpenSUSE (or at least Ubuntu packages)

**Comment by clapbr** [comment]
> Great! :)
> You are right about packaging, that was my intention from the beginning. I guess it'll be systemd "friendly" once the issue #1 is closed. Since, for systemd daemons fprintf(stderr, fmt, ...) is preferred instead of syslog() (my plan is to use syslog() only if -b is given). But first I'll update the documentation (including a TODO list).
> 
> After that I will provide packages for multiple Linux distributions using The Open Build Service (OBS) by OpenSUSE (or at least Ubuntu packages)

Cool, I can help with the AUR package once those small things are ready. That will cover Arch, Manjaro, Antergos, Netrunner etc. For now I've been using sudoers to be able to start it in my xprofile but that´s not package-friendly. With systemd it should be easier to enable or disable it as a service.

**Comment by germag** [comment]
That will be great. I'll be traveling for a couple of weeks, I'll do the changes ASAP. 
I'm closing this issue, if there is any problem please reopen it.
