### ISSUE TITLE
event_loop.c:31:21: fatal error: libudev.h: No such file or directory

### ISSUE THREAD

**Issue by pankaj-kvhld** [germag/clicklockd#3]
When I run "make"

How to solve this problem?

**Comment by clapbr** [comment]
Search your distro repository for libudev or libudev-dev.

**Comment by pankaj-kvhld** [comment]
I am a complete newbie to Linux :(
Could you please instruct me a bit more. Thanks a lot.

**Comment by clapbr** [comment]
> I am a complete newbie to Linux :(
> Could you please instruct me a bit more. Thanks a lot.

Sure, what's your distro, Ubuntu?

**Comment by pankaj-kvhld** [comment]
Thank you very much, I am using Ubuntu 16.04.

**Comment by clapbr** [comment]
> Thank you very much, I am using Ubuntu 16.04.

try this: 
`sudo apt-get install libudev-dev`

**Comment by pankaj-kvhld** [comment]
WOW, this did the trick. Can't thank you enough. 

If I may ask, how did learn Linux? Could you recommend any good book to start?

**Comment by clapbr** [comment]
> WOW, this did the trick. Can't thank you enough.
> 
> If I may ask, how did learn Linux? Could you recommend any good book to start?

A good way to start is learning to use the command line, after you understand the basics everything else depends on it and will be easier then. This book (https://www.amazon.com/gp/product/111898384X/ref=as_li_tl?ie=UTF8&camp=1789&creative=9325&creativeASIN=111898384X&linkCode=as2&tag=29834000-20&linkId=264733f640b3cff9a18b489580dfc7b4) will teach you that and also how to automate common tasks with shell scripts, which is also one of the most useful Linux skills and builds upon your command line knowledge.

**Comment by pankaj-kvhld** [comment]
Thank you very much, very helpful. Book ordered :)
I will close the issue.

**Comment by Riya-Singhal15** [comment]
Hii @clapbr , I have similar issue in Centos 8, I've tried sudo yum install libudev-dev but it is giving - 
No match for argument: libudev
Error: Unable to find a match: libudev

I also tried it with dnf but still the same. Can you please tell me how to solve this?

**Comment by germag** [comment]
> Hii @clapbr , I have similar issue in Centos 8, I've tried sudo yum install libudev-dev but it is giving - No match for argument: libudev Error: Unable to find a match: libudev
> 
> I also tried it with dnf but still the same. Can you please tell me how to solve this?

Hi @Riya-Singhal15 

It seems that in CentOS 8 /Fedora you need to do:
`sudo dnf install libgudev-devel`
