### ISSUE TITLE
just want to say Thank You, and the issue i found so far.

### ISSUE THREAD

**Issue by jason5545** [germag/clicklockd#5]
II have a Cerebral palsy when I was born, and because of the disease, I have a lImIted movement wIth my body(basIcally only RIght Index fInger Is usable.) so I have tried Linux a few years ago, but at the end, I need to switch back to wIndows, because the click-lock feature Is lackIng In most dIstros( I know Ubuntu has such feature, but CanonIcal Isn't my taste.) so recently I gave Manjaro a try, and I really loved it, so I start to find the click-lock alternatIve, after some IntensIve googlIng I  fInally found  here, just want to say a huge Thank you for your awesome work.
and here Is some Issue I ran Into:
I currently use a ThinkPad T430, It has a Trackpad and TrackPoint when I use the clIcklockd, only the TrackPoint has worked as Intended, but the Trackpad doesn't, Is there a chance to fix thIs Issue？ thanks again 

Operating System: Manjaro Linux 
KDE Plasma Version: 5.16.4
KDE Frameworks Version: 5.61.0
Qt Version: 5.13.0
Kernel-Version: 5.2.11-1-MANJARO
OS Type: 64-bit
Processors: 8 × Intel® Core™ i7-3740QM CPU @ 2.70GHz
Memory: 15.4 GiB

**Comment by germag** [comment]
Hi Jason,
I’m happy to help.
I'll try to reproduce this issue using the manjaro's kde version. I'll check on you asap.

**Comment by jason5545** [comment]
Thanks. just let me know if you need any additional info from my end.

**Comment by germag** [comment]
Hi @jason5545,
Could you try the last version and see if your touchpad works?

**Comment by jason5545** [comment]
it works perfectly. just curious do I have any way to give you a small amount of donation?  just an appreciation for your hard work.  :)

**Comment by germag** [comment]
Hi,
Thank you I highly appreciate it :), but it is not necessary any donation.

I'm closing this issue, please reopen it if there are any problems.
