### ISSUE TITLE
Wayland (Plasma)

### ISSUE THREAD

**Issue by clapbr** [germag/clicklockd#6]
Do you think this can be made to work in Wayland with a few changes? It seems wayland actually recognizes our virtual device but behavior gets really messed up, I don't have the expertise to know why. If you have any machine running wayland could take a look at it whenever you feel like? Thanks

**Comment by germag** [comment]
In "theory" there should be no problem, since it doesn't use anything from X. But I never checked to be honest. Anyway I'll take a look and try to fix any problem.

**Comment by clapbr** [comment]
Took a try at Plasma Wayland again, it seems our virtual device shows up on Mouse settings disabled at first. Enabling it will make mouse double-click instead of a single click, and the lock doesn't actually works.
Is there anything I can do to provide better debug info?

Many distros are already defaulting to Wayland, and ppl might need this for acessibility. I'm still holding onto X for the meanwhile though, but still can help testing. Just wanna make sure clicklockd is future-proof, as I'm pretty sure at least someone else might need it, I can't be the only quadriplegic trackball user using Linux.

**Comment by germag** [comment]
thanks for taking the time of testing this.

IIRC you are using arch, I'm right?, I'm currently using clicklockd with wayland in fedora (gnome3) and I don't see any problem, I'll check with plasma and arch. It's weird because clicklockd doesn't depend on X, it uses the uinput infrastructure in the kernel. So I'll try with plasma, if I'm not able to reproduce I'll add some debugging info for you to try.

**Comment by clapbr** [comment]
Yeah I'm on Arch but I have systems with Fedora/Ubuntu to test on if needed. 

Just tried on Gnome and it works fine there indeed.

Taking a quick look at input handling source for Plasma, Gnome and wlroots it seems each Wayland compositor implement input in slightly differently ways.

If you confirm there isn't much to do on clicklockd's side I can open issues directly on the affected compositors/DE's.

**Comment by germag** [comment]
> Yeah I'm on Arch but I have systems with Fedora/Ubuntu to test on if needed.
> 
> Just tried on Gnome and it works fine there indeed.
> 
> Taking a quick look at input handling source for Plasma, Gnome and wlroots it seems each Wayland compositor implement input in slightly differently ways.

Could you point me to the Plasma input handling code?

> If you confirm there isn't much to do on clicklockd's side I can open issues directly on the affected compositors/DE's.

Sometimes it's only a matter of getting the supported events right, so the virtual mouse is recognized as a valid device, for instance, even if we only send the BTN_LEFT (or BTN_RIGHT) we need to support the relative movement, or it will not be recognized as a mouse in all cases. Although the virtual mouse already supports virtually everything, so don't know what could be missing.

thanks,

**Comment by clapbr** [comment]
> 
> Could you point me to the Plasma input handling code?
> 
Relevant parts are here: https://invent.kde.org/plasma/kwin/-/blob/master/src/pointer_input.cpp
>
>Sometimes it's only a matter of getting the supported events right, so the virtual mouse is recognized as a valid device, for instance, even if we only send the BTN_LEFT (or BTN_RIGHT) we need to support the relative movement, or it will not be recognized as a mouse in all cases. Although the virtual mouse already supports virtually everything, so don't know what could be missing.

It recognizes as a pointer device, although needs to be enabled manually on Plasma Mouse settings. 
It also shows up on `qdbus org.kde.KWin /KWin org.kde.KWin.showDebugConsole` and I can see events from both devices (real+virtual) on `sudo libinput debug-events --verbose`.

This is a shot in the dark, but I think Plasma may be (mis)interpreting the press/release events from both devices separately, so we get two clicks on every click instead of the intended behavior. This seems to break the following assumption from https://wayland.freedesktop.org/libinput/doc/latest/seats.html : 
`if the same button is released on one device, the button should be considered logically down if still down on another device.`

Thanks !

**Comment by germag** [comment]
> It recognizes as a pointer device, although needs to be enabled manually on Plasma Mouse settings. It also shows up on `qdbus org.kde.KWin /KWin org.kde.KWin.showDebugConsole` and I can see events from both devices (real+virtual) on `sudo libinput debug-events --verbose`.
> 
> This is a shot in the dark, but I think Plasma may be (mis)interpreting the press/release events from both devices separately, so we get two clicks on every click instead of the intended behavior. This seems to break the following assumption from https://wayland.freedesktop.org/libinput/doc/latest/seats.html : `if the same button is released on one device, the button should be considered logically down if still down on another device.`


Mmm seems plausible, clicklockd work on that assumption. If possible with an extra mouse, by holding one button down in one mouse, it should be possible to drag with the other mouse.

Ok, I'll check this and see if I can work around it or not

**Comment by clapbr** [comment]
A possible solution is to add a --mirror flag on which we'd mirror all button and move events from the real pointer device, turning it into a complete mouse replacement... but that sounds non-optimal and may have latency side-effects.

Maybe you can come up with a better workaround though it seems the real solution is for Plasma to behave as expected, guess I'll open an issue there for that.

**Comment by clapbr** [comment]
Hey have you looked at this yet? Planning to migrate to Wayland soon as my new rig is a dual-gpu setup and its working much better there.
When you do, let me know your initial diagnosis so I can report something meaningful for the Plasma and sway/wlroots devs.

**Comment by germag** [comment]
> Hey have you looked at this yet? Planning to migrate to Wayland soon as my new rig is a dual-gpu setup and its working much better there. When you do, let me know your initial diagnosis so I can report something meaningful for the Plasma and sway/wlroots devs.

Yes, but I was unable to make it work, I'll try to find a Plasma developer to help me with this.

**Comment by germag** [comment]
The only thing that I have not tried (yet (*)) is creating a virtual mouse using wlr_virtual_pointer

(*) I'm trying to avoid that, since will be wayland specific and AFAIK does not work on all compositors

**Comment by clapbr** [comment]
Hey, what's up @germag. 

Any chance you can take another look at this? Plasma 6 is out and Wayland is (finally) running better than X11 on most aspects I'd say, but I still miss clicklockd :(

**Comment by germag** [comment]
> Hey, what's up @germag.
> 
> Any chance you can take another look at this? Plasma 6 is out and Wayland is (finally) running better than X11 on most aspects I'd say, but I still miss clicklockd :(

Yes, I asked some kde developers (no response), I'll try again

**Comment by clapbr** [comment]
> > Hey, what's up @germag.
> > Any chance you can take another look at this? Plasma 6 is out and Wayland is (finally) running better than X11 on most aspects I'd say, but I still miss clicklockd :(
> 
> Yes, I asked some kde developers (no response), I'll try again

Hey, hope you're doing well. Just letting you know I opened an issue about this on KDE bug tracker (https://bugs.kde.org/show_bug.cgi?id=486034).

**Comment by germag** [comment]
> > > Hey, what's up @germag.
> > > Any chance you can take another look at this? Plasma 6 is out and Wayland is (finally) running better than X11 on most aspects I'd say, but I still miss clicklockd :(
> > 
> > 
> > Yes, I asked some kde developers (no response), I'll try again
> 
> Hey, hope you're doing well. Just letting you know I opened an issue about this on KDE bug tracker (https://bugs.kde.org/show_bug.cgi?id=486034).

Thanks!, I'll follow that issue

**Comment by clapbr** [comment]
Hey! Took a shot at trying to fix it, not sure if it will ever be comitted but at least I have it working for now and looks simple to fix.

Can you take a look at the MR? https://invent.kde.org/plasma/kwin/-/merge_requests/5696

**Comment by germag** [comment]
> Hey! Took a shot at trying to fix it, not sure if it will ever be comitted but at least I have it working for now and looks simple to fix.
> 
> Can you take a look at the MR? https://invent.kde.org/plasma/kwin/-/merge_requests/5696

Yes, I'm following that MR, thanks!

**Comment by clapbr** [comment]
Hey, the MR got merged, so next Plasma release clicklockd will work. Closing and marking this as fixed !

**Comment by germag** [comment]
> Hey, the MR got merged, so next Plasma release clicklockd will work. Closing and marking this as fixed !

Great! thank you
