### ISSUE TITLE
how to stop

### ISSUE THREAD

**Issue by alimsk** [germag/clicklockd#7]
thanks for making this awesome software.

I accidentally set the timeout to 1.5ms, and you know now I'm in trouble.
**how do i stop clickclockd?**

edit:
it's not on system monitor.
I've also killed the process using this command:
sudo kill `cat /var/run/clickclockd.pid`
but still

**Comment by germag** [comment]
Hi, 
If you have the last version, run this:

kill -9 $(cat /var/run/clicklockd.pid)

(replace the pid file with the one passed as -p argument, if any).
Let me know if it worked.

BTW, since I have a new job, I plan to make proper packages for ubuntu, fedora and arch. That I hope will fix issues like this.

**Comment by alimsk** [comment]
that file is not in var/run.
i did that command before, but without the `-9` argument (if that matters),
exactly like this:
`sudo kill $(cat /var/run/clicklockd.pid`
now when I try to do it again (with `-9`):
``` sh
$ sudo kill -9 `cat /var/run/clicklockd.pid`
cat: /var/run/clicklockd.pid: No such file or directory

Usage:
  kill [options] <pid> [...]

Options:
  <pid> [...] send signal to every <pid> listed
  -<signal>, -s, --signal <signal>
                         specify the <signal> to be sent
  -l, --list=[<signal>] list all signal names, or convert one to a name
  -L, --table list all signal names in a nice table

  -h, --help display this help and exit
  -V, --version output version information and exit

For more details see kill(1).
```

**Comment by germag** [comment]
Mmmm did you passed any filaname as -p?

Anyways try:

killall -s 9 clicklockd

or 
ps -ax | grep clicklockd

and use the pid number with:
kill -9 pid_number

**Comment by germag** [comment]
Sorry I forget to tell you, the -9 matters, since the default kill signal is TERM, and clicklockd captures that signal.

**Comment by alimsk** [comment]
this command:
`killall -s 9 clicklockd`
work.

Thank you very much :smile:

**Comment by germag** [comment]
is nothing :).
Could you tell me what linux distribution you use?

**Comment by alimsk** [comment]
i use Ubuntu 20.04 LTS.
```sh
$ uname -a
Linux mypc 5.8.0-50-generic #56~20.04.1-Ubuntu SMP Mon Apr 12 21:46:35 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by germag** [comment]
Thanks
