### ISSUE TITLE
Segmentation fault on Debian

### ISSUE THREAD

**Issue by Silejonu** [germag/clicklockd#8]
I successfully compiled `clicklockd`, but when I run it, I get the following:

```bash
silejonu@debian:~/clicklockd$ sudo ./clicklockd 
Segmentation fault
```

This is on Debian 11, up-to-date. I tried with Cinnamon and GNOME Wayland with the same results.

This works flawlessly on Fedora 36.

Here is the output of `# grep clicklockd /var/log/syslog`:
```
Nov  2 23:23:59 debian clicklockd: Init with timeout: 2s 0us
Nov  2 23:23:59 debian kernel: [   29.983456] clicklockd[1902]: segfault at 556600000000 ip 00007f062779ab15 sp 00007ffc0629c828 error 4 in libudev.so.1.7.0[7f0627793000+19000]
```

**Comment by germag** [comment]
Hi, I'll try to reproduce it in a VM. In fedora 36 the libudev it's a bit older, I need to check if something has changed.
Thanks,

**Comment by Silejonu** [comment]
Let me know if I can help you troubleshoot in any way. I have no C skills though, otherwise I would have searched for a fix.

**Comment by Silejonu** [comment]
I tested installing `libudev-dev` from `backports`, and I get the same error:

```
Jan  6 14:27:49 debian clicklockd: Init with timeout: 2s 0us
Jan  6 14:27:49 debian kernel: [  182.600801] clicklockd[1446]: segfault at 55d800000000 ip 00007fd8a84a8975 sp 00007fff8eee5a48 error 4 in libudev.so.1.7.4[7fd8a84a4000+1a000]
```

This is the same libudev version as on Fedora 37, which works fine.

**Comment by germag** [comment]
@Silejonu coul you try the `change-optimization-level` branch, or you can just change this line in the `Makefile`
```
CFLAGS=-c -O -Wall -Wextra -D_GNU_SOURCE
```
to this:
```
CFLAGS=-c -O2 -Wall -Wextra -D_GNU_SOURCE
```

note the `-O2` 


let me know if works

**Comment by Silejonu** [comment]
It does work, thank you!

I just tested it successfully on Debian 11 GNOME, Debian 11 Cinnamon, and Fedora Workstation 37.  
If this is helpful to you, I can also make sure it works on other distros before you push the change to the main branch.

**Comment by germag** [comment]
> It does work, thank you!
> 
> I just tested it successfully on Debian 11 GNOME, Debian 11 Cinnamon, and Fedora Workstation 37. If this is helpful to you, I can also make sure it works on other distros before you push the change to the main branch.

Yes please, but in any case I'll keep this issue open because that's not a real solution, I need to figure out what's happening inside the libudev. And maybe it's time to replace it with sd-device since libudev is deprecated

Thanks

**Comment by Silejonu** [comment]
I'm coming back to report on my testing. I have tested the following distros:

- Debian 11 (Cinnamon + GNOME)
- Fedora 37
- Ubuntu 22.04
- CentOS Stream 9 (GNOME)
- Arch Linux 2023-02-23 (GNOME)
- Linux Mint 21.1 (XFCE)
- openSUSE Tumbleweed 2023-02-22 (KDE Plasma)

All of them are working with the `-O2` flag during compilation.

openSUSE has issues with `CC=c99`, though. I'll open a separate bug report about it.

**Comment by germag** [comment]
Wow, thank you! I'll address issue #12 in the PR #11
